# -*- coding: utf-8 -*-
"""leetcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ok9OyAJ89UEreq7BAMfN3_TpuE8RR4So
"""

class Solution(object):
    def maximumAmount(self, coins):
        '''logic:
        max money to get reaching bottom right that is Annth item if we can nutralize 2 robbers '''
        m=len(coins)
        n=len(coins[0])
        dynamic=[[[float("-inf")]* 3 for i in range(n)] for j in range(m)]
        for i in range(m):
            for j in range(n):
                for k in range(3):
                    gr=coins[i][j]
                    if i==0 and j==0:
                        dynamic[i][j][k]=gr
                        if gr<0 and k>0:
                            dynamic[i][j][k]=max(dynamic[i][j][k],0)
                        continue
                    reset=float("-inf")
                    if i>0:
                        reset=max(dynamic[i-1][j][k],reset)
                    if j>0:
                        reset=max(dynamic[i][j-1][k],reset)
                    dynamic[i][j][k]=reset+gr
                    if gr<0 and k>0:
                        re=float("-inf")
                        if i>0:
                            re=max(re,dynamic[i-1][j][k-1])
                        if j>0: re=max(dynamic[i][j-1][k-1],re)
                        dynamic[i][j][k]=max(dynamic[i][j][k],re)
        return max(dynamic[m-1][n-1])